# Generated by Django 4.2.1 on 2023-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.FloatField(default=0.0)),
                ("purchaser_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("purchase_date", models.DateTimeField(verbose_name="date purchased")),
            ],
        ),
        migrations.DeleteModel(name="Date",),
        migrations.DeleteModel(name="Price",),
        migrations.DeleteModel(name="Purchaser",),
        migrations.AddField(
            model_name="item", name="price", field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(name="Quantity",),
        migrations.AddField(
            model_name="transaction",
            name="quantity_of_item",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="shop.item"
            ),
        ),
    ]
